# SProxy2 Configuration
# Generated automatically

[proxies.Hitachigymnasiet]
listen_address = "100.73.107.5"
listen_port = 1081
bind_port = 22
proxy_type = "socks5"
run_on_startup = true

[proxies.Homelab]
listen_address = "10.9.0.1"
listen_port = 22
bind_port = 1080
proxy_type = "socks5"
ssh_username = "gustav"
run_on_startup = true
